[build]
  command = "bun install && cd frontend && bun install && bun run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.1.30"
  NODE_ENV = "production"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/posts/*"
  to = "/.netlify/functions/posts/:splat"
  status = 200

[[redirects]]
  from = "/api/comments/*"
  to = "/.netlify/functions/comments/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "bun run dev"
  port = 3000
  publish = "frontend/dist"
